### ISSUE TITLE
编译报错，能不能给个说明文档呢？

### ISSUE THREAD

**Issue by yxw839841231** [jiangjingming/springboot-study#2]
`job.setJobGroup(jobDO.getJobGroup());
            job.setJobName(jobDO.getJobKey());
            job.setCronExpression(jobDO.getJobCronExpress());
            job.setDesc(jobDO.getJobGroup() + job.getJobName());`

对应的get方法并不存在，是没提交么？
`query.createCriteria().andJobGroupEqualTo()`
and方法也没找到

**Comment by jiangjingming** [comment]
`对应的get方法并不存在，是没提交么？
query.createCriteria().andJobGroupEqualTo()
and方法也没找到`
这个是指的那个类的那个地方的代码，我这边全文搜索并没有看到，你能具体截图或者指明吗

**Comment by yxw839841231** [comment]
不晓得怎么⏫图片 。就说明下位置吧。
QurtzServiceImpl 148行 ：
/**
     * 任务初始化
     * @return
     */
    @Override
    @Transactional
    @ExceptionNotice(noticeRemarks = "任务初始化")
    public Boolean initQuartzData() 
EarlywarningQuartzServiceImpl 132行
private QuartzJob queryQurzJob(EarlyWarningTaskDTO earlyWarningTaskDTO, JobStatusEnum jobStatusEnum) 



选了两个 其他还有好几个 主要是核心模块的定时器那一块

**Comment by yxw839841231** [comment]
![image](https://user-images.githubusercontent.com/13757119/33229816-aa7665f2-d211-11e7-9ab3-6a15a7d3dc4a.png)
![image](https://user-images.githubusercontent.com/13757119/33229820-c3e28534-d211-11e7-9164-b8e26580e94f.png)

**Comment by jiangjingming** [comment]
你那边没有装lomBok的插件吧，我有空的时候写个部署的文档吧

**Comment by jiangjingming** [comment]
你有钉钉吗？加我钉钉号：jiangjingming
