### ISSUE TITLE
SpringBoot+Maven多模块打包问题

### ISSUE THREAD

**Issue by vicent88** [jiangjingming/springboot-study#3]
按现在项目SpringBoot+Maven多模块结构，打jar包或者打war包都会出问题吧？

**Comment by jiangjingming** [comment]
不会出问题啊，是否maven下载依赖的jar包全了，application 可以直接启动项目的，打成jar java -jar也可以启动起来

**Comment by vicent88** [comment]
不知道你有没有发现打出来的jar包特别大，里面的依赖重复引用了
